/**
 *  version.h
 *
 *  Auto-generated by cmake.
 *
 *  @copyright 2023 Copernica BV
 */

/**
 *  Include guard
 */
#pragma once

#define AMQPCPP_VERSION_MAJOR ( @VERSION_MAJOR@ +0 )
#define AMQPCPP_VERSION_MINOR ( @VERSION_MINOR@ +0 )
#define AMQPCPP_VERSION_PATCH ( @VERSION_PATCH@ +0 )

#define AMQPCPP_VERSION ( AMQPCPP_VERSION_MAJOR << 16 | AMQPCPP_VERSION_MINOR << 8 | AMQPCPP_VERSION_PATCH )
